<a href="https://colab.research.google.com/github/jungddddd/ML2/blob/main/2)%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EB%AA%A8%EB%8D%B8_%EB%B6%84%EB%A5%9801_naive_baysian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 나이브베이즈
#### iris 분류

In [ ]:
# 필요한 모듈 불러오기
# 데이터 분석을 위한 pandas 모듈 불러오기
# Scikit-learn 의 datasets 모듈 불러오기
# sklearn.model_selection 의 train_test_split 함수 불러오기
import pandas as pd

from sklearn import datasets
from sklearn.model_selection import train_test_split

In [ ]:
# datasets의 load_iris() 함수사용
# iris 데이터를 불러와 iris 변수에 할당
iris = datasets.load_iris()

In [ ]:
# iris 데이터 확인
# data, target,  target_names 등의 데이터를 딕셔너리 형식으로 확인 가능
iris

In [ ]:
# DESCR(description) 을 이용해 iris 데이터셋과 관련된 정보 확인
print(iris.DESCR)

In [ ]:
# iris 데이터셋에서 data를 dataframe 형식으로 변경하여 iris_df 에 할당. columns 파라미터 이용해 컬럼명을 feature_names 으로 지정
# iris 데이터셋에서 target을 iris_df에 컬럼명 target 으로 추가
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df["target"] = pd.DataFrame(iris.target)
iris_df.head()

In [ ]:
# info() 함수 이용해 데이터 정보 확인
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [ ]:
# describe() 함수 이용해 기초통계량 확인
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [ ]:
# train_test_split() 함수 이용해 데이터 분할
# train, test 데이터 분할 확인
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    test_size = 0.3,
                                                    random_state = 102)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(105, 4) (45, 4) (105,) (45,)


In [ ]:
# 나이브베이즈 모델 생성
# sklearn.naive_bayes 모듈의 GaussianNB 사용
from sklearn.naive_bayes import GaussianNB

In [ ]:
# GaussianNB()함수로 나이브베이즈 모델을 생성해 clf 에 할당
# fit 함수 이용해 train 데이터로 학습 시킴
clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [ ]:
# 생성된 모델에 test 데이터를 넣어 예측
# 예측된 값은 y_pred 변수에 할당
y_pred = clf.predict(x_test)

In [ ]:
# 예측된 값 확인
y_pred

array([0, 2, 1, 1, 2, 0, 0, 0, 1, 1, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2,
       1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1,
       2])

In [ ]:
# predict_proba() 함수는 클래스에 대한 확률을 출력
# x_test 데이터를 이용해 0, 5, 10 데이터의 클래스에 대해 분류될 확률을 확인
# 0번 데이터는 클래스 0으로 분류될 확률이 1.00000000e+000 (약 1)로 가장 높음
# 5번 데이터는 클래스 0으로 분류될 확률이 1.00000000e+000 (약 1)로 가장 높음
# 10번 데이터는 클래스 2으로 분류될 확률이 9.72315099e-001 (약 0.9)로 가장 높음
clf.predict_proba(x_test)[[0, 5, 10]]

array([[1.00000000e+000, 4.10124155e-020, 2.78599016e-028],
       [1.00000000e+000, 2.70419041e-019, 4.42868293e-027],
       [1.36690654e-121, 2.76849012e-002, 9.72315099e-001]])

In [ ]:
# predict() 함수는 최종적인 예측값 출력
# x_test 데이터를 이용해 0, 5, 10 데이터의 최종 예측값 확인
# 0번 데이터는 클래스 0으로 분류
# 5번 데이터는 클래스 0으로 분류
# 10번 데이터는 클래스 2로 분류
clf.predict(x_test)[[0, 5, 10]]

array([0, 0, 2])

In [ ]:
# 모델의 성능 확인
# sklearn.metrics 모듈의 confusion_matrix 함수와 accuracy_score, classification_report 함수 불러오기
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
# 실제값인 y_test 와 예측값인 y_pred 를 비교
# confusion_matrix() 함수를 이용
cfmat = confusion_matrix(y_test, y_pred)
print(cfmat)

[[17  0  0]
 [ 0 10  2]
 [ 0  2 14]]


In [ ]:
# 실제값인 y_test 와 예측값인 y_pred 를 비교
# accuracy_score() 함수 이용
acc = accuracy_score(y_test, y_pred)
print(acc)

0.9111111111111111


- prior 추가

In [ ]:
# GaussianNB()함수로 priors 추가한 나이브베이즈 모델을 생성해 clf2 에 할당
# GaussianNB() 함수에 priors 파라미터를 이용해 사전지식을 더해줌. 가중치와 비슷한 의미
# 분류가 애매한 경우 클래스 2 로 분류하도록 지정
# fit 함수 이용해 train 데이터로 학습 시킴
clf2 = GaussianNB(priors = [1/100, 1/100, 98/100])
clf2.fit(x_train, y_train)

GaussianNB(priors=[0.01, 0.01, 0.98])

In [ ]:
# 생성된 모델에 test 데이터를 넣어 예측
# 예측된 값은 y_pred2 변수에 할당
y_pred2= clf2.predict(x_test)

In [ ]:
# 실제값인 y_test 와 예측값인 y_pred2 를 비교
# confusion_matrix() 함수를 이용
cfmat2 = confusion_matrix(y_test, y_pred2)
print(cfmat2)

[[17  0  0]
 [ 0  7  5]
 [ 0  1 15]]


In [ ]:
# 실제값인 y_test 와 예측값인 y_pred 를 비교한 confusion matrix와 비교
print(cfmat)

[[17  0  0]
 [ 0 10  2]
 [ 0  2 14]]


In [ ]:
# 실제값인 y_test 와 예측값인 y_pred2 를 비교
# accuracy_score() 함수 이용
acc2 = accuracy_score(y_test, y_pred2)
print(acc2)

0.8666666666666667


- classification_report
  - Precision : 정밀도
      - 양성 클래스라고 예측한 샘플(TP+FP) 중 실제로 양성 클래스에 속하는 샘플(TP) 샘플 수의 비율.
      - 높을수록 좋음. '예측값'을 기준으로 한 '정답인 예측값'의 비율

  - Recall : 재현율
    - 실제 양성 클래스에 속한 샘플(TP+FN) 중 양성 클래스라고 예측한 샘플(TP) 샘플 수의 비율.
    - 높을수록 좋음. '실제 값'을 기준으로 한 '정답인 예측값'의 비율

  - 정밀도와 재현율은 상충 관계에 있어서, 마치 시소 게임처럼 정밀도가 높아지면 재현율이 낮아지고, 반대로 재현율이 높아지면 정밀도는 낮아짐

  - Accuracy : 정확도
    - 전체 샘플 중 맞게 예측한 샘플 수의 비율. 높을수록 좋다.

  - F1-score
    - precision과 recall의 가중 조화평균(weight harmonic average)
    - 정밀도와 재현율이 균형있게 둘 다 높을 때 F-1 점수도 높게 나타남.
    - 정밀도와 재현율이 모두 중요한 경우에는 F-1 점수를 사용해서 모델을 평가

  - support
    - 각 라벨의 실제 샘플 개수

  - macro avg
    - 평균에 평균을 내는 개념. 단순 평균.
    - 각 클래스 별로 동일한 가중치를 부여한다. 즉 샘플 개수의 불균형을 고려하지 않음
    - 샘플 개수의 불균형을 고려하지 않기 때문에 소수 클래스에 대한 성능이 낮을 때 더 큰 페널티가 발생(데이터가 불균형할 때 확인해보자)

  - weighted avg
    - 각 클래스에 속하는 표본의 개수로 가중 평균을 내서 계산하는 방법.
    - 샘플 개수의 불균형을 고려
    - 가중 평균을 수행하기 때문에 샘플의 개수가 적은 클래스의 영향력이 감소


In [ ]:
# classification_report()를 이용해 실제값(y_test)와 예측값(y_pred) 비교 결과 출력하기
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.83      0.83      0.83        12
           2       0.88      0.88      0.88        16

    accuracy                           0.91        45
   macro avg       0.90      0.90      0.90        45
weighted avg       0.91      0.91      0.91        45



In [ ]:
# classification_report()를 이용해 실제값(y_test)와 예측값(y_pred2) 비교 결과 출력하기
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.88      0.58      0.70        12
           2       0.75      0.94      0.83        16

    accuracy                           0.87        45
   macro avg       0.88      0.84      0.84        45
weighted avg       0.88      0.87      0.86        45



### <과제> 나이브베이즈(가우시안)를 이용
#### 와인 등급을 예측하는 모델을 만들고, 모델 성능을 평가하시오.
- prior 값을 변경하면서 성능비교

datasets.load_wine() 으로 데이터를 불러와 사용

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

In [ ]:
wine = datasets.load_wine()

In [ ]:
print(wine.DESCR)

In [ ]:
print(wine.keys())

In [ ]:
wine.data

In [ ]:
wine.target

In [ ]:
df_wine = pd.DataFrame(wine.data, columns = wine.feature_names)

In [ ]:
df_wine.head()

In [ ]:
df_wine.shape

In [ ]:
df_wine.info()

In [ ]:
df_wine.describe()

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target,
                                                    test_size = 0.3,
                                                    random_state = 103)

print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

In [ ]:
clf = GaussianNB()
clf.fit(x_train, y_train)

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
y_pred

In [ ]:
cfmat = confusion_matrix(y_test, y_pred)
print(cfmat)

In [ ]:
acc = accuracy_score(y_test, y_pred)
print(acc)

In [ ]:
clf2 = GaussianNB(priors = [10/100, 80/100, 10/100])
clf2.fit(x_train, y_train)

In [ ]:
y_pred2 = clf2.predict(x_test)

In [ ]:
cfmat2 = confusion_matrix(y_test, y_pred2)
print(cfmat2)

In [ ]:
acc2 = accuracy_score(y_test, y_pred2)
print(acc2)